# Generated by Django 5.1.5 on 2025-02-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
