# Generated by Django 5.1.5 on 2025-02-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_signin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='un',
        ),
    ]
