# Generated by Django 5.1.5 on 2025-02-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_remove_signin_un'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='password',
            new_name='pa',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='username',
            new_name='us',
        ),
    ]
