# Generated by Django 5.1.5 on 2025-02-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Lastname',
            new_name='subject',
        ),
    ]
