# Generated by Django 5.1.5 on 2025-02-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_customuser_remove_property_area_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Signup',
        ),
    ]
