# Generated by Django 5.1.5 on 2025-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_customuser_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100)),
                ('em', models.EmailField(max_length=100)),
                ('da', models.DateField()),
                ('ti', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
